[alembic]
script_location = apps/api/alembic
prepend_sys_path = apps/api
path_separator = os
sqlalchemy.url = postgresql://unused

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys =

[logger_root]
level = WARN
handlers =
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic
